from pathlib import Path

path = Path('/home/ubuntu/innovare-os/client/src/pages/Rocket.tsx')
text = path.read_text()

text = text.replace("type TaskPriority = 'baixa' | 'media' | 'alta' | 'critica';\n", "type TaskPriority = 'baixa' | 'media' | 'alta' | 'critica';\ntype RocketTaskStatus = 'pendente' | 'andamento' | 'concluida';\n")

text = text.replace("  status: 'pendente' | 'andamento' | 'concluida';\n  checklist: { id: string; text: string; done: boolean }[];\n};", "  status: RocketTaskStatus;\n  checklist: { id: string; text: string; done: boolean }[];\n  statusHistory: { status: RocketTaskStatus; author: string; at: string; note: string }[];\n};")

text = text.replace("const DELIVERY_STYLE: Record<DeliveryStatus, string> = {", "const TASK_STATUS_STYLE: Record<RocketTaskStatus, string> = {\n  pendente: 'border-slate-500/30 bg-slate-500/10 text-slate-200',\n  andamento: 'border-cyan-500/30 bg-cyan-500/10 text-cyan-200',\n  concluida: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200',\n};\n\nconst TASK_STATUS_LABEL: Record<RocketTaskStatus, string> = {\n  pendente: 'Pendente',\n  andamento: 'Em progresso',\n  concluida: 'Concluído',\n};\n\nconst DELIVERY_STYLE: Record<DeliveryStatus, string> = {")

text = text.replace("    checklist: [\n      { id: 'ck-1', text: 'Separar feedbacks por subsistema', done: true },\n      { id: 'ck-2', text: 'Criar lista de ajustes obrigatórios', done: false },\n      { id: 'ck-3', text: 'Validar riscos técnicos antes da fabricação', done: false },\n    ],\n  },", "    checklist: [\n      { id: 'ck-1', text: 'Separar feedbacks por subsistema', done: true },\n      { id: 'ck-2', text: 'Criar lista de ajustes obrigatórios', done: false },\n      { id: 'ck-3', text: 'Validar riscos técnicos antes da fabricação', done: false },\n    ],\n    statusHistory: [\n      { status: 'pendente', author: 'Gabriel', at: '2026-02-01 09:00', note: 'Demanda criada após a submissão de design.' },\n      { status: 'andamento', author: 'Larissa', at: '2026-02-02 16:20', note: 'Primeiro item do checklist confirmado.' },\n    ],\n  },")

text = text.replace("    checklist: [\n      { id: 'ck-4', text: 'Definir massa e envelope do sistema', done: false },\n      { id: 'ck-5', text: 'Planejar teste de ejeção', done: false },\n      { id: 'ck-6', text: 'Registrar evidências no sistema', done: false },\n    ],\n  },", "    checklist: [\n      { id: 'ck-4', text: 'Definir massa e envelope do sistema', done: false },\n      { id: 'ck-5', text: 'Planejar teste de ejeção', done: false },\n      { id: 'ck-6', text: 'Registrar evidências no sistema', done: false },\n    ],\n    statusHistory: [\n      { status: 'pendente', author: 'Laura', at: '2026-02-04 11:10', note: 'Checklist aberto para planejamento de recuperação.' },\n    ],\n  },")

text = text.replace("        checklist: checklist.length ? checklist : [{ id: `ck-${Date.now()}`, text: 'Confirmar entendimento da demanda', done: false }],\n      };", "        checklist: checklist.length ? checklist : [{ id: `ck-${Date.now()}`, text: 'Confirmar entendimento da demanda', done: false }],\n        statusHistory: [{ status: 'pendente', author: activeUserName, at: new Date().toLocaleString('pt-BR'), note: 'Demanda criada pela Innovare Team.' }],\n      };")

old_toggle = """      const nextChecklist = task.checklist.map((item) => item.id === checklistId ? { ...item, done: !item.done } : item);\n      const completed = nextChecklist.every((item) => item.done);\n      nextTaskStatus = completed ? 'concluida' : 'andamento';\n      persistedStatus = completed ? 'concluida' : 'em_progresso';\n      return { ...task, checklist: nextChecklist, status: nextTaskStatus };\n"""
new_toggle = """      const nextChecklist = task.checklist.map((item) => item.id === checklistId ? { ...item, done: !item.done } : item);\n      const completed = nextChecklist.every((item) => item.done);\n      nextTaskStatus = completed ? 'concluida' : 'andamento';\n      persistedStatus = completed ? 'concluida' : 'em_progresso';\n      const statusChanged = task.status !== nextTaskStatus;\n      return {\n        ...task,\n        checklist: nextChecklist,\n        status: nextTaskStatus,\n        statusHistory: statusChanged ? [\n          { status: nextTaskStatus, author: activeUserName, at: new Date().toLocaleString('pt-BR'), note: completed ? 'Checklist concluído pelo time responsável.' : 'Checklist atualizado e demanda em progresso.' },\n          ...task.statusHistory,\n        ] : task.statusHistory,\n      };\n"""
text = text.replace(old_toggle, new_toggle)

insert_after = """  const reviewDelivery = async (deliveryId: string | number, status: 'aprovado' | 'reprovado' | 'ajustes') => {\n"""
mark_ok = """  const markTaskOk = async (taskId: string | number) => {\n    const previousTasks = tasks;\n    setTasks((current) => current.map((task) => task.id === taskId ? {\n      ...task,\n      status: 'concluida',\n      checklist: task.checklist.map((item) => ({ ...item, done: true })),\n      statusHistory: [\n        { status: 'concluida', author: activeUserName, at: new Date().toLocaleString('pt-BR'), note: 'Time confirmou conclusão pelo botão Marcar como OK.' },\n        ...task.statusHistory,\n      ],\n    } : task));\n\n    if (typeof taskId === 'number') {\n      try {\n        await updateRocketTaskStatusMutation.mutateAsync({ taskId, status: 'concluida' });\n      } catch (error) {\n        setTasks(previousTasks);\n        toast.error('Não foi possível persistir a conclusão da demanda Rocket.');\n        return;\n      }\n    }\n\n    toast.success('Demanda marcada como concluída pelo time.');\n  };\n\n"""
text = text.replace(insert_after, mark_ok + insert_after)

old_render = """return <div key={task.id} className=\"rounded-xl border border-white/10 bg-slate-950/70 p-4\"><div className=\"flex items-start justify-between gap-3\"><div><p className=\"font-bold text-white\">{task.title}</p><p className=\"mt-1 text-sm text-slate-400\">{task.description}</p></div><span className={`rounded border px-2 py-1 text-xs font-bold capitalize ${PRIORITY_STYLE[task.priority]}`}>{task.priority}</span></div><div className=\"mt-3 flex flex-wrap gap-2 text-xs text-slate-400\"><span className=\"flex items-center gap-1\"><UserRound className=\"h-3 w-3\" /> {task.assignedTo.join(', ')}</span><span className=\"flex items-center gap-1\"><CalendarDays className=\"h-3 w-3\" /> {formatDate(task.dueDate)}</span><span className=\"flex items-center gap-1\"><Target className=\"h-3 w-3\" /> {completion}%</span></div><div className=\"mt-3 h-1.5 rounded-full bg-white/10\"><div className=\"h-full rounded-full bg-cyan-400\" style={{ width: `${completion}%` }} /></div><div className=\"mt-3 space-y-2\">{task.checklist.map((item) => <label key={item.id} className=\"flex cursor-pointer items-center gap-2 rounded bg-white/5 px-3 py-2 text-sm text-slate-300\"><input type=\"checkbox\" checked={item.done} onChange={() => toggleChecklist(task.id, item.id)} /> <span className={item.done ? 'line-through opacity-60' : ''}>{item.text}</span></label>)}</div></div>;"""
new_render = """return <div key={task.id} className=\"rounded-xl border border-white/10 bg-slate-950/70 p-4\"><div className=\"flex items-start justify-between gap-3\"><div><p className=\"font-bold text-white\">{task.title}</p><p className=\"mt-1 text-sm text-slate-400\">{task.description}</p></div><div className=\"flex flex-col items-end gap-2\"><span className={`rounded border px-2 py-1 text-xs font-bold capitalize ${PRIORITY_STYLE[task.priority]}`}>{task.priority}</span><span className={`rounded border px-2 py-1 text-xs font-bold ${TASK_STATUS_STYLE[task.status]}`}>{TASK_STATUS_LABEL[task.status]}</span></div></div><div className=\"mt-3 flex flex-wrap gap-2 text-xs text-slate-400\"><span className=\"flex items-center gap-1\"><UserRound className=\"h-3 w-3\" /> Responsáveis: {task.assignedTo.join(', ')}</span><span className=\"flex items-center gap-1\"><CalendarDays className=\"h-3 w-3\" /> {formatDate(task.dueDate)}</span><span className=\"flex items-center gap-1\"><Target className=\"h-3 w-3\" /> {completion}%</span></div><div className=\"mt-3 h-1.5 rounded-full bg-white/10\"><div className=\"h-full rounded-full bg-cyan-400\" style={{ width: `${completion}%` }} /></div><div className=\"mt-3 space-y-2\">{task.checklist.map((item) => <label key={item.id} className=\"flex cursor-pointer items-center gap-2 rounded bg-white/5 px-3 py-2 text-sm text-slate-300\"><input type=\"checkbox\" checked={item.done} onChange={() => toggleChecklist(task.id, item.id)} /> <span className={item.done ? 'line-through opacity-60' : ''}>{item.text}</span></label>)}</div><Button onClick={() => markTaskOk(task.id)} disabled={task.status === 'concluida'} className=\"mt-3 w-full bg-emerald-600 text-xs hover:bg-emerald-700 disabled:opacity-60\"><CheckCircle2 className=\"mr-2 h-4 w-4\" /> Marcar como OK</Button><div className=\"mt-3 rounded-lg border border-white/10 bg-white/5 p-3\"><p className=\"text-xs font-bold uppercase tracking-[0.18em] text-slate-400\">Histórico de mudanças de status</p><div className=\"mt-2 space-y-2\">{task.statusHistory.map((entry, index) => <div key={`${task.id}-history-${index}`} className=\"text-xs text-slate-400\"><span className=\"font-semibold text-cyan-200\">{TASK_STATUS_LABEL[entry.status]}</span> por {entry.author} em {entry.at}: {entry.note}</div>)}</div></div></div>;"""
if old_render not in text:
    raise SystemExit('Bloco de renderização de tarefas não encontrado')
text = text.replace(old_render, new_render)

path.write_text(text)
